//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gale.REST {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gale.REST.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application:default.
        /// </summary>
        internal static string GALE_CONNECTION_DEFAULT_KEY {
            get {
                return ResourceManager.GetString("GALE_CONNECTION_DEFAULT_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://gale.azurewebsites.net/.
        /// </summary>
        internal static string GALE_DOCS_SITE {
            get {
                return ResourceManager.GetString("GALE_DOCS_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a {0} model..
        /// </summary>
        internal static string SwasbuckleExtension_Blueprint_DELETE {
            get {
                return ResourceManager.GetString("SwasbuckleExtension_Blueprint_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a list of {0} model records (OData Convention&apos;s)..
        /// </summary>
        internal static string SwasbuckleExtension_Blueprint_GET {
            get {
                return ResourceManager.GetString("SwasbuckleExtension_Blueprint_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data can be filtered with ODATA Conventions (Queryable).
        ///
        ///For more ODATA information visit: &lt;a target=&quot;_blank&quot; href=&quot;{0}&quot;&gt;{0}&lt;/a&gt;..
        /// </summary>
        internal static string SwasbuckleExtension_Blueprint_GET_ImplementationNotes {
            get {
                return ResourceManager.GetString("SwasbuckleExtension_Blueprint_GET_ImplementationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a new {0} model..
        /// </summary>
        internal static string SwasbuckleExtension_Blueprint_POST {
            get {
                return ResourceManager.GetString("SwasbuckleExtension_Blueprint_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new {0} model recod,  (The model schema exclude all fiellds wich has marked as &quot;Auto Generated Value&quot;).
        /// </summary>
        internal static string SwasbuckleExtension_Blueprint_POST_ImplementationNotes {
            get {
                return ResourceManager.GetString("SwasbuckleExtension_Blueprint_POST_ImplementationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update a {0} model..
        /// </summary>
        internal static string SwasbuckleExtension_Blueprint_PUT {
            get {
                return ResourceManager.GetString("SwasbuckleExtension_Blueprint_PUT", resourceCulture);
            }
        }
    }
}
